[package]
name = "lua_mathematics"
version = "0.1.1"
edition = "2021"

[dependencies]
rlua = { version = "*" }
#serde_json = { version = "*" }
#serde = { version = "*", features = ["derive"] }
mlua = "*"
paste = "*"